//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public string MaNV { get; set; }
        public string MaQuyen { get; set; }
        public string TenNV { get; set; }
        public Nullable<bool> Phai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChiNV { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> SoDienThoaiNV { get; set; }
        public string MatKhauNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
